name: Text validation

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run text
      run: |
        pip install text-validator
        validate-text text-validator-b.toml text/apology.txt
        validate-text text-validator.toml text/crito.txt
        validate-text text-validator.toml text/euthyphro.txt
        validate-text text-validator.toml text/meno.txt
        validate-text text-validator.toml text/phaedo.txt
        validate-text text-validator.toml text/ion.txt
        validate-text text-validator-b.toml text/republic.txt
        validate-text text-validator-b.toml text/symposium.txt
